# Generated by Django 6.0.5 on 2026-05-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('espece', models.CharField(max_length=120)),
                ('couleur', models.CharField(max_length=80)),
                ('date_observation', models.DateField()),
                ('lieu', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
