# Generated by Django 6.0.5 on 2026-05-06 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echanges', '0002_papillon_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePapillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('papillon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='echanges.papillon')),
            ],
        ),
        migrations.CreateModel(
            name='SituationGeographique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('papillon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='echanges.papillon')),
            ],
        ),
    ]
