# Generated by Django 6.0.5 on 2026-05-07 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('race', models.CharField(blank=True, max_length=120)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('couleur', models.CharField(blank=True, max_length=80)),
                ('particularite', models.TextField(blank=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('provenance', models.CharField(blank=True, max_length=120)),
                ('pays', models.CharField(blank=True, max_length=120)),
                ('continent', models.CharField(blank=True, max_length=120)),
                ('regime_alim', models.CharField(blank=True, max_length=120)),
                ('taille_aquarium', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(max_length=80)),
                ('source_id', models.PositiveIntegerField()),
                ('adopted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Adoption',
        ),
        migrations.AddField(
            model_name='animal',
            name='espece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animaux', to='adoptions.espece'),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(fields=('source', 'source_id'), name='unique_animal_source'),
        ),
    ]
