# Generated by Django 6.0.5 on 2026-05-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PapillonReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papillon_source_id', models.PositiveIntegerField(unique=True)),
                ('nom', models.CharField(max_length=120)),
                ('espece', models.CharField(max_length=120)),
                ('couleur', models.CharField(max_length=80)),
                ('date_observation', models.DateField(blank=True, null=True)),
                ('provenance', models.CharField(max_length=120)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source', models.CharField(default='elevage_papillons', max_length=120)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
