# Generated by Django 6.0.5 on 2026-05-07 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('espece', models.CharField(max_length=120)),
                ('couleur', models.CharField(max_length=80)),
                ('date_observation', models.DateField()),
                ('provenance', models.CharField(max_length=120)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adopted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePapillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('papillon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='papillons.papillon')),
            ],
        ),
        migrations.CreateModel(
            name='SituationGeographique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('papillon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='papillons.papillon')),
            ],
        ),
    ]
